apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app

spec:
  replicas: 5
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app

    spec:
      containers:
        - name: thirsty-darwin
          image: de.icr.io/in-re/inventory-management
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
              protocol: TCP